# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identify.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eidentify.proto\"\"\n\x0cImageRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"=\n\rImageResponse\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x18\n\x07objects\x18\x02 \x03(\x0b\x32\x07.Object\")\n\x06Object\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02\x32=\n\x0cImageService\x12-\n\x0cProcessImage\x12\r.ImageRequest\x1a\x0e.ImageResponseB\x0bZ\t.;serviceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'identify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\t.;service'
  _globals['_IMAGEREQUEST']._serialized_start=18
  _globals['_IMAGEREQUEST']._serialized_end=52
  _globals['_IMAGERESPONSE']._serialized_start=54
  _globals['_IMAGERESPONSE']._serialized_end=115
  _globals['_OBJECT']._serialized_start=117
  _globals['_OBJECT']._serialized_end=158
  _globals['_IMAGESERVICE']._serialized_start=160
  _globals['_IMAGESERVICE']._serialized_end=221
# @@protoc_insertion_point(module_scope)
